esphomeyaml:
  name: lednick
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout
  on_boot:
    then:
      - light.turn_on: nicklight

wifi:
  ssid: !secret ssid
  password: !secret password
  manual_ip:
    static_ip: 192.168.178.25
    gateway: 192.168.178.1
    subnet: 255.255.255.0
  

logger:

ota:

api:

web_server:

output:
  - platform: esp8266_pwm
    pin: GPIO14
    frequency: 1000 Hz
    id: red
  - platform: esp8266_pwm
    pin: GPIO5
    frequency: 1000 Hz
    id: green
  - platform: esp8266_pwm
    pin: GPIO12
    frequency: 1000 Hz
    id: blue
  - platform: esp8266_pwm
    id: arilux_blue_led
    pin:
      number: GPIO2
      inverted: True
  

light:
  - platform: rgb
    name: "Nick verlichting"
    id: nicklight
    red: red
    green: green
    blue: blue
  - platform: monochromatic
    name: "Arilux blue LED"
    output: arilux_blue_led